//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class svyaz
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> datazapisi { get; set; }
        public string pol { get; set; }
        public string messagetrevogi { get; set; }
        public string telephone { get; set; }
    }
}
